# Generated by Django 2.2.16 on 2022-04-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220414_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
